### ISSUE TITLE
DotNetExe.FullPath returns null for .NET Global Tool

### ISSUE THREAD

**Issue by jerriep** [natemcmaster/CommandLineUtils#101]
**Describe the bug**
The `DotNetExe.FullPath` property return `null` for .NET Global Tools. Specifically, in the case of running the project via `dotnet` command this works fine. But when you package the project and install it as a .NET Global Tool it does not work.

It appears that this is due to the following section of code:
https://github.com/natemcmaster/CommandLineUtils/blob/447b3e17a72fcd085d341f60c225ab6eaa434651/src/CommandLineUtils/Utilities/DotNetExe.cs#L49-L54

In the case of a .NET Global Tool that `MainModule` property refers to the executable of the actual .NET Global Tool, and not the `dotnet` executable.

**To Reproduce**
Create a simple .NET Global tool which prints `DotNetExe.FullPath` to the console, and you will see that it outputs null. **Note** that you need to actually install it as a global tool

**Expected behavior**
Expect it to have the correct path to the `dotnet` executable

**Additional context**
To be honest, I am not even sure in which case one needs the full path to the `dotnet` executable. Since this did not work, I tried to simply execute the `dotnet` command (without any path) and it worked fine. Here is my code:
https://github.com/jerriep/dotnet-outdated/blob/32a275d03aa5bbb44ba3de334717a2e85eb46dc8/src/DotNetOutdated/Services/DotNetRunner.cs#L16-L23

I tested on Windows, Mac and Linux and had no problems. So maybe I do not understand the potential issues when doing it like this and not specifying the full path to the `dotnet` executable?

**Comment by natemcmaster** [comment]
This is expected behavior. `DotNetExe.FullPath` is only meant to return a path if we can positively identify the exact `dotnet.exe` file used to launch the current process. It does so in a way that doesn't probe PATH because the current process may not have been launched from the `dotnet` on PATH. Global tools use a custom app host, so we cannot definitely determine which dotnet to use just by looking at the current process. Consider using `DotNetExe.FullPathOrDefault()` instead which will return just `"dotnet"` if it can't find the `dotnet.exe` file.

That said, in .NET Core 2.1, custom app hosts will honor the `DOTNET_ROOT` environment variable. We could add this as a fallback check.

**Comment by jerriep** [comment]
Thanks, Nate 💯
