### ISSUE TITLE
Add pre-execute configuration methods

### ISSUE THREAD

**Issue by liamdawson** [natemcmaster/CommandLineUtils#103]
**Is your feature request related to a problem? Please describe.**
In an app I'm maintaining at work, I'm using `OnValidate` to set application configuration before subcommands are executed. I'd prefer not to overload a method that's supposed to be for something else, but I could not find another method that was always called before a subcommand would be executed.

**Describe the solution you'd like**
A `OnCommandExecuting`/`OnCommandExecutingAsync` pair, which happens after validation, and can be used to wrap the actual execution (quasi-middleware).

**Describe alternatives you've considered**
I've used `OnValidate`, but it feels like it would surprise future developers maintaining what I've written.

**Comment by liamdawson** [comment]
I've been working on this, and I think the best place to start (for something usable) is to take advantage of the `OnParsingComplete` callback.

**Comment by natemcmaster** [comment]
I'd like to understand the scope of the problem better since - at first glance - I'm not sure this is something we need in the library. I'm curious what ideas you've explored already and what motivated the choice to implement #106.

I agree using `OnValidate` is probably not the best way to perform pre-execute logic. There may be other ways though. For example, have you considered writing your own `IConvention` implementation? You could use this to add a method call that decorates `OnExecute`.

Or, you could use inheritance and require all subcommands to implement it, for example:
```csharp
abstract class MyCommandBase
{
   protected void OnExecute()
   {
      // do pre-execute stuff here
      this.Run();
      // do post execute here
   }

   protected abstract void Run();
}
```

Not saying no...just trying to understand better the need to address.

**Comment by natemcmaster** [comment]
One drawback I see to tapping into OnParsingComplete is that pre-execute logic would executed before validation, and would run even if validation errors will be produced (which would prevent the call to OnExecute.) Also, anything run during OnParsingComplete may happen before all conventions have been applied. For example, the conventions for populating properties and fields with values run as a part of OnParsingComplete. These may not have run yet.

**Comment by atruskie** [comment]
Just to chime in with my own experience, I've used the multiple inheritance model example you suggested in my own code.

**Comment by natemcmaster** [comment]
For now, I think inheritance offers the most straightforward pattern for running pre/post execute logic and doesn't require you to implement `IConvention`. A middleware-type application model would be more composable and may be coming in the future, but I haven't committed to a design yet.
