### ISSUE TITLE
3.0.0: Unifying to .NET Standard 2.0 - dropping .NET Framework and .NET Standard 1.6

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/CommandLineUtils#118]
In 3.0.0, I plan to stop cross-compiling this library for .NET Framework and .NET Standard 1.6, leaving .NET Standard 2.0 as the only target framework for this library.

### My thinking
* .NET Framework was added because .NET Standard 2.0 was immature and had issues on .NET Framework. Those have gone away as .NET Framework 4.7.2 fully implements .NET Standard 2.0
* .NET Standard 1.6 was added only to support .NET Core 1.x. Now that .NET Core 2.1 is the new LTS, I do not find supporting .NET Core 1.x compelling.

### For current .NET Framework and .NET Standard 1.6 consumers
Your way forward here is to upgrade to .NET Core 2.x and .NET Framework >= 4.6.1. I would have recommended this anyways to keep your app up to date with the latest APIs from Microsoft

**Comment by jcaillon** [comment]
Hello Nate,

I don't know if you are aware of that problem so I'm commenting here.

**The problem I see:**

> Your way forward here is to upgrade to .NET Core 2.x and .NET Framework >= 4.6.1. I would have recommended this anyways to keep your app up to date with the latest APIs from Microsoft.

I totally agree that .net 4.6.1 should be the new *minimum version* as it is, to my knowledge, the version shipped with the latest release of windows 10 and thus it is the most widely installed version atm. However, I think it is best not to target higher than 4.6.1 to ensure that a maximum number of users will be able to use the software without having to install a new version of the .net framework.

**That being said**, if this library targets only .net standard 2.0, the requirement for .net framework consumers is to upgrade their project to **4.7.2** (and not 4.6.1).

**Why?** According to this [net-implementation-support table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support), we should be able to make libraries target netstandard2.0 as v4.6.1 implements net standard 2.0. *This works*, **BUT** it doesn't work as expected. 

The issue is depicted / explained in this short video:

https://www.youtube.com/watch?v=u67Eu_IgEMs&list=PLRAdsfhKI4OWx321A_pr-7HhRNk7wOLLY&index=8

The issue is also discussed here:

- https://stackoverflow.com/questions/47365136/why-does-my-net-standard-nuget-package-trigger-so-many-dependencies/47366401#47366401
- also for reference on pb with nuget : https://github.com/dotnet/standard/issues/481

**Personal opinion:**

Your library can drop net standard 1.6 but should continue to target a .net framework version (4.5 or 4.6.1?) while 4.7.2 is not the go-to version.


Best regards and a happy end-of-year to you.

**Comment by natemcmaster** [comment]
Thanks for feedback @jcaillon. This is a scenario I've thought about and was [the original reason I added a net45 target](https://github.com/natemcmaster/CommandLineUtils/commit/ad1707a29e44f9272f74d44eaa6f33fc7d794f1a). Now that net472 is out and has largely fixed compat problems with netstandard, I'd really like to simplify this library to a single TFM.

That said, do you know of any reason why consumers _can't_ upgrade their projects to target net472?

**Comment by natemcmaster** [comment]
Ok, you've changed my mind. At this point, I'm not planning TFM changes. I'm not promising I won't ever, but I don't have compelling reasons now. Not worth breaking anyone just for the sake of smaller packages and fewer #if defs.
