### ISSUE TITLE
DotNetExe does not work on Mac when using as Global Tool

### ISSUE THREAD

**Issue by stefandevo** [natemcmaster/CommandLineUtils#125]
When you create a .net core global tool with this package, and try to use `var dotnet = DotNetExe.FullPath;` you get an empty string.

**Comment by natemcmaster** [comment]
That's sort of by design. DotNetExe.FullPath is meant to be the patch to dotnet.exe used to start the current process. When running as a global tool, your process is not actually started via dotnet.exe, but instead, uses a special copy of the .NET Core app host. This means the API can't actually identify where dotnet.exe is. 

As a fallback, consider using DotnetExe.FullPathOrDefault()

https://github.com/natemcmaster/CommandLineUtils/blob/c723427e82899d161e2825295b9cf2e0fe3da4c4/src/CommandLineUtils/Utilities/DotNetExe.cs#L33-L39

**Comment by stefandevo** [comment]
Okay but basically I wanted to execute a dotnet command so I need the location. But thanks for explaining.

**Comment by natemcmaster** [comment]
If you just do `Process.Start("dotnet")`, .NET will still find and use the dotnet on PATH. Typically, this will be good enough.

**Comment by stefandevo** [comment]
Ok thanks. That's indeed working.
