### ISSUE TITLE
Boolean property not parsing correctly unless CommandOptionType.SingleValue specified as an attribute.

### ISSUE THREAD

**Issue by hpractv** [natemcmaster/CommandLineUtils#129]
**Describe the bug**
When I have a boolean property type and specify a valid true/false string as an arg, it tells me `Unrecognized command or argument 'true'`.  If I add the argument for `CommandOptionType.SingleValue`, it parses the string value correctly.

**To Reproduce**
1. Using this version of the library '2.2.5'
2. Run this code :
```
 [Option("-v|--Verbose",
            Description = "Extended/detailed output messaging. Defaults to false.")]
        public bool Verbose { get; }
```
3. With these arguments :
```
new string[] { "-v", "true" };
```
4. See error `Unrecognized command or argument 'true'`

**Expected behavior**
When the code is changed to this:
```
[Option("-v|--Verbose",
            "Extended/detailed output messaging. Defaults to false.",
            CommandOptionType.SingleValue)]
        public bool Verbose { get; }
```

The expected result of of `Verbose` is `true`.  I would expect that this extra atrribute param wouldn't have the effect of parsing the value correctly.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by natemcmaster** [comment]
This behavior is by design. It's not something that we can change as it would be a breaking change for many users.

Just to clarify, the `Unrecognized command or argument 'true'` error you see is because, by default, boolean properties are considered `CommandOptionType.NoValue`. These are considered flags (aka switches). Just specifying the flag means `true`, otherwise `false`


```
[Option("-v|--Verbose")]
public bool Verbose { get; }
```

Inputs |  Value of `Verbose`
----|---
(not specified) | `false`
`--verbose` | `true`

When you override the default option type to `CommandOptionType.SingleValue`, you get different behavior.

```
[Option("-v|--Verbose", CommandOptionType.SingleValue)]
public bool Verbose { get; }
```

Inputs | Value of `Verbose`
----|---
 (not specified) | `false`
`--verbose` | Invalid. Value expected after `--verbose`.
`--verbose true` | `true`
`--verbose false` | `false`
`--verbose banana` | Error. Cannot parse `"banana"` into `System.Boolean`.

This matches what you would see if "Verbose" were a string type.

```
[Option("-v|--Verbose", CommandOptionType.SingleValue)]
public string Verbose { get; }
```

Inputs | Value of `Verbose`
----|---
 (not specified) | `null`
`--verbose` | Invalid. Value expected after `--verbose`.
`--verbose true` | `"true"`
`--verbose false` | `"false"`
`--verbose banana` | `"banana"`


Hope that helps,
-Nate

**Comment by hpractv** [comment]
This does help.  I was checking through the samples and the unit tests to see something like this and couldn't find this level of detail.  Thanks!

**Comment by natemcmaster** [comment]
Good to know. I'm going to put this into docs.
