### ISSUE TITLE
Auto prompt required fields when empty

### ISSUE THREAD

**Issue by DavidDeSloovere** [natemcmaster/CommandLineUtils#141]
(if this exists, I couldn't find docs or sample about it)

Would be great to have required fields automatically prompted be OnExecute(Async)

**Comment by natemcmaster** [comment]
This feature doesn't exist. I'd consider a PR for it. Let me know if you're willing to contribute.

**Comment by DavidDeSloovere** [comment]
I might give it a go, if you can point me in the right direction (or the direction you see this going) maybe.

An [AutoPrompt] attribute ? If the value is null, we auto prompt.

**Comment by natemcmaster** [comment]
I'd like to look at some different options. I'm open to suggestions, and I haven't decided yet what the API might look like for this. 

Here are some additional ideas:

Maybe "Interactive" instead of "AutoPrompt"? 

This might belong on `ParserSettings` (new in 2.3, unreleased). 
```c#
new ParserSettings()
{
    // prompt, if necessary, for required information
    Interactive = true
}
```

Or maybe CommandLineApplication? It's not my favorite idea since the API in this class is getting cluttered.
```c#
var app = new CommandLineApplication();
app.Interactive = true;
```

I think we may also need to make `Required` a first-class property of CommandOption/Argument. We'll need to do this due to the order in which evaluation/validation/parsing happens.

**Comment by DavidDeSloovere** [comment]
Closed it in favor of https://github.com/natemcmaster/CommandLineUtils/issues/152
