### ISSUE TITLE
Using HostBuilder create CommandLineApplication through DI

### ISSUE THREAD

**Issue by michael-x** [natemcmaster/CommandLineUtils#185]
**Is your feature request related to a problem? Please describe.**
I'm trying to use CommandLineApplication in ConfigureServices to get connection string parameters (Server/Database) for a database connection that is configured in DI. However the CommandLineApplication is constructed in the CommandLineService and not added to the services collection.

**Describe the solution you'd like**
Move the logic from the CommandLineService constructor into HostBuilderExtensions.RunCommandLineApplicationAsync. This allows the CommandLineApplication to be added to the service collection as a singleton via a factory method. The CommandLineService can then take a simple dependency on CommandLineApplication.

**Describe alternatives you've considered**
Haven't found a proper way to access the CommandLineApplication, Options or Arguments in ConfigureServices.

**Additional context**

**Comment by michael-x** [comment]
I've been thinking about another approach: I would love to see the parsing and validation of the command line and the execution of the command as separate things, where the execution becomes optional.

For example a new set of ParseAndValidate methods could be used to do all the parsing and validation and to return a properly initialized command object (not requiring DI or anything like that). A set of Execute methods taking such a command object could invoke the command.

The information on the command returned by ParseAndValidate can then be used to configure logging, DI, etc. Afterwards the command could be executed. There are two models how this could work:

1. Dual use classes: Use one instance of the class initialized with a constructor without parameters to determine command line parameters during ParseAndValidate. Use another instance of the class resolved from a DI container to execute the command.

2. Separate command handlers: Implement the execution logic of the command in a separate handler class and invoke the appropriate handler for the command separately, e.g. through a mechanism like MediatR.

**Comment by TheConstructor** [comment]
I don't know whether or not #182 would help with this…

**Comment by natemcmaster** [comment]
> Haven't found a proper way to access the CommandLineApplication, Options or Arguments in ConfigureServices.

This is sort of by design. I'm being very conservative in this first release of generic-host integration by trying to minimize the API added and keep the usages fairly limited. I'm anticipating improvements in the future once we've been able to better factor application execution from parsing.

> I would love to see the parsing and validation of the command line and the execution of the command as separate things, where the execution becomes optional.

This is the approach I'm planning to take in 3.0. This piece of feedback has been given in various ways over the last few years of this library. After I finish up 2.3, I plan to start taking on big changes.

**Comment by michael-x** [comment]
We are currently trying a different approach. In order to have full control on how the application is composed (e.g. logging, connections strings, DI, other behavior) based on whatever has been specified on the command line, we now do the entire command line parsing before we build the host.

```C#
CommandLineApplication<Program> app = new CommandLineApplication<Program>();
app.Conventions.UseDefaultConventions();

ParseResult parseResult = app.Parse(args);
CommandLineApplication command = parseResult.SelectedCommand;
if (command.IsShowingInformation)
    return ExitCode.Success.Value;
// Work around GetValidationResult being internal
MethodInfo method = command
    .GetType()
    .GetMethod("GetValidationResult",
        BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
ValidationResult validationResult = (ValidationResult)method.Invoke(command, new object[0]);
if (validationResult != ValidationResult.Success)
    return command.ValidationErrorHandler(validationResult);

object commandModel = ((IModelAccessor)command).GetModel();
// ExitCode is a struct holding the exit code. IRequest<T> is a MediatR request.
IRequest<ExitCode> request = (IRequest<ExitCode>)commandModel;
...
```

That is we
* Instantiate a root `CommandLineApplication<Program>` and tell it to use default conventions.
* Parse the command line and retrieve the selected command.
* Determine, if the command is just showing information and exit, if that is the case.
* Validate the command and exit, if that is not successful.
* Get the proper command model.

Afterwards we can add `app`, `command` and `request` to DI and build and run the host like so:

```C#
using (IHost host = hostBuilder.Build())
{
    IMediator mediator = host.Services.GetRequiredService<IMediator>();
    // In case we want to do background work
    //await host.StartAsync();
    ExitCode exitCode = await mediator.Send(request);
    // In case we want to do background work
    //await host.StopAsync();
    return exitCode.Value;
}
```

In our case we are (currently) not running any background tasks, while the command is executed, so we just invoke our code and exit. Another option would be to create a hosted service that invokes the mediator and to use `hostBuilder.RunConsoleAsync()` to run the application.

There are two problems with our approach:
1. Unfortunately this currently requires a call to the non-public `GetValidationResult` method. It would be great, if that method was public.
2. We need to cast the command to the `IModelAccessor` to get the command model and we need to cast the command model to the correct type. It would be great, if there was a method GetModel<T>() that returns the model as type T, if that is possible, or throws otherwise.

I wonder, whether it would be possible to expose GetValidationResult and/or provide a GetModel<T>() method on the CommandLineApplication. Would be willing to contribute.

**Comment by michael-x** [comment]
We've updated to 2.3.0 RC and the `GetValidationResult` works like a charm.

Unfortunately Markdown swallowed my generic parameter. `GetModel()` should of course have been `GetModel<T>()` (I've rectified this). The intention would be to return the model, if it is of an appropriate type and to throw otherwise. This would help in situations where all models derive from the same base class or implement the same interface. Worst case a consumer could call `GetModel<object>()` and do whatever necessary with the result.

An implementation could look something like:

``````C#
public static TModel GetModel<TModel>(this CommandLineApplication command)
{
    if (!(command is IModelAccessor accessor))
        throw new InvalidOperationException($"Cannot access the model of the {command.GetType()} command.");
    object commandObject = accessor.GetModel();
    if (commandObject == null)
        throw new InvalidOperationException($"No model for the {command.GetType()} command.");
    if (!(commandObject is TModel model))
        throw new InvalidOperationException($"The command model {commandObject.GetType()} is not a valid request returning an exit code");
    return model;
}
``````

**Comment by rcdailey** [comment]
> This is the approach I'm planning to take in 3.0. This piece of feedback has been given in various ways over the last few years of this library. After I finish up 2.3, I plan to start taking on big changes.

I'm new to the library, and I know this issue is quite old, but I'm wondering now that we are at 3.1.0 in the present day, how do I achieve this?

My struggle right now is that the command model (the one with the `[Command]` attribute) also has the `OnExecuteAsync()` method, which unfortunately tightly couples my business logic with the command line argument data. I'd like the two separated, especially for testing purposes.

The documentation is pretty sparse and unhelpful for this. How have the two been separated?

**Comment by mpoettgen** [comment]
As you can see from my alter ego's comment above on 18 December 2018 you do not have to use CommandLineUtils to execute commands. Therefore you do not need to have an `OnExecuteAsync` method on your command model.
You can look at your command model as a request to execute a particular command with corresponding parameters. You can then say that the command implementation is a handler for that request. The mediator pattern implemented by https://github.com/jbogard/MediatR/wiki can glue those together for you. Make your `MyCommand` command model implement `IRequest<ExitCode>` and your `MyCommandHandler` implement `IRequestHandler<MyCommand, ExitCode>`.

**Comment by rcdailey** [comment]
Thank you @mpoettgen this is really helpful. However, I'm not sure how to implement `OnExecuteAsync()`. Is this the right way?

```cs
[Command(Description = "Description")]
public class MyCommand : BaseCommand, IRequest
{
    private readonly IMediator _mediator;

    public MyCommand(IBaseCommandProvider provider, IMediator mediator)
        : base(provider)
    {
        _mediator = mediator;
    }

    [Option(Description = "help text")]
    public bool MyOption { get; set; }

    protected override Task OnExecuteAsync(CommandLineApplication app)
    {
        return _mediator.Send(this);
    }
}
```

I thought it might need async/await but that doesn't work here, because of my return type (`Task`). Not sure the right way to do this. Never used MediatR before.

**Comment by mpoettgen** [comment]
@rcdailey when you don't use CommandLineUtils to execute your command, but instead only use it to parse and validate the command model, then you don't need to implement `OnExecute` or `OnExecuteAsync` on your command model. You implement the handler instead.

**Comment by rcdailey** [comment]
But someone has to send the request, right? That doesn't just happen magically, does it? How does my handler know which command was run by the user if I don't send it via `OnExecute()`?

**Comment by rcdailey** [comment]
I read over the 18th December 2018 comment examples again, and it helped a lot more now that I understand what is going on. I think I may have a working example here:

```cs
private static int Main(string[] args)
{
    try
    {
        var app = new CommandLineApplication<TrashCommand>();
        app.Conventions.UseDefaultConventions();

        var parseResult = app.Parse(args);
        var command = parseResult.SelectedCommand;
        if (command.IsShowingInformation)
        {
            return 0;
        }

        var result = command.GetValidationResult();
        if (result != ValidationResult.Success)
        {
            return command.ValidationErrorHandler(result);
        }

        var container = CompositionRoot.Setup(command.GetModel<BaseCommand>());

        var mediator = container.Resolve<IMediator>();
        mediator.Send(command.GetModel<object>());

        // var result = app.Execute(args);
        Log.CloseAndFlush();
        return 0;
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
        return 1;
    }
}
```

The only odd part is that, the `GetModel<T>()` extension method is mostly useless because, without using `OnExecute()`, you can't reasonably know which concrete command type to ask for without violating open/closed principle. However, MediatR seems to be just happy with an `object` and it knows the underlying type and invokes the correct handler.

Let me know if I'm still missing the mark. And thanks for your help so far!

**Comment by mpoettgen** [comment]
The idea is for all your command models to implement `IRequest<ExitCode>` (they do not need to be derived from `BaseCommand`, unless there is something in `BaseCommand` that applies to all commands). You would then get the `model` via `command.GetModel<IRequest<ExitCode>>()` and send that to MediatR.
Beforehand you would register all your handlers (implementing `IRequestHandler<,>`) with DI, so that MediatR can resolve them. Additionally you may register your command model with DI, if you need it to be injected anywhere.

**Comment by rcdailey** [comment]
Thank you again. Everything is working so far except I don't see where ExitCode comes from.

**Comment by mpoettgen** [comment]
That's up to you. You can define an enum with all the different exit codes of your tool.

**Comment by mpoettgen** [comment]
@natemcmaster would you be interested in a PR for the missing generic `GetModel<T>()` extension method and maybe an example somewhere?

**Comment by natemcmaster** [comment]
Here's my suggestion -- if you, try writing a wrapper around this library for your specific use cases. Here's a little class I wrote for unit testing a long time ago, but I didn't think it was generally useful enough to put into the main, supported API of the project: https://github.com/natemcmaster/CommandLineUtils/blob/fbc8668c136fe624ac8da8ea4454202d157f9601/test/CommandLineUtils.Tests/Utilities/CommandLineParser.cs#L13-L29

I'm still not sure about adding `GetModel<T>()`. As mentioned above, this doesn't really work well with generics because the compiler can't know which subcommand will be resolved at runtime. But it's also been several years since I've thought much about this code, so I'm open to suggestions. Sometimes documentation and sample code is better than trying to build an API in a library that works for everyone, so I'm also open to more samples and docs.
