### ISSUE TITLE
CommandLineApplication.Option doesn't support hierarchical keys

### ISSUE THREAD

**Issue by cwchapma** [natemcmaster/CommandLineUtils#233]
**Describe the bug**
When trying to add an commandline option, with a colon in the key, I get an ArgumentException: `Invalid template pattern: '-x:--dataserver:hostname <hostname>'`

**To Reproduce**
1. Using this version of the library '2.3.4'
2. Run this code:
```c#
var app = new CommandLineAppliation();
app.Option("-x|--dataserver:hostname <hostname>", "dataserver:hostname", CommandOptionType.SingleValue);
```
4. See ArgumentException

**Expected behavior**
This option format is supported by configuration.commandline and it is useful for adding options to support setting hierarchical configuration.

**Comment by cwchapma** [comment]
I'm interested in creating a PR for this.  The an option might be to make the separators [here](https://github.com/natemcmaster/CommandLineUtils/blob/master/src/CommandLineUtils/CommandOption.cs#L32) configurable but I'm guessing there might be a better solution or a reason this is a bad idea.

Any suggestions @natemcmaster?

**Comment by natemcmaster** [comment]
Actually the code you would need to change is here: https://github.com/natemcmaster/CommandLineUtils/blob/be230400aaae2f00b29dac005c1b59a386a42165/src/CommandLineUtils/Internal/CommandLineProcessor.cs#L404. Separators can't be option-specific since when looking at the raw input, the processor doesn't know yet _which_ option we're looking at. But I would be okay making separators a global setting that can be configured.

**Comment by natemcmaster** [comment]
Closing this in favor of https://github.com/natemcmaster/CommandLineUtils/issues/252. I think the simplest solution here would be allow configuration of which characters are considered special or not. I've prototyped a solution which would allow you to to use `:` in the option name. See the prototype here https://github.com/natemcmaster/CommandLineUtils/commit/d31b8f518d6fae8d9320729ca19c228419f388c1
