### ISSUE TITLE
Execute can only be called once on CommandLineApplication

### ISSUE THREAD

**Issue by shockliang** [natemcmaster/CommandLineUtils#253]
**Describe the bug**
I wrote a console app skeleton that using thread to keep running and passing the user input to `CommandLineApplication` to execute command.
The command will not execute anymore after showing help.

**To Reproduce**
1. type `someCommand -h`
2. type `someCommand` 

**Expected behavior**
The command will be executed.

**Screenshots**
N/A

**Additional context**
Sample repo: https://github.com/shockliang/console-app-skeleton
I found the `IsShowingInformation` property was set to true and not going back to false anymore. Is my misunderstand?

**Comment by natemcmaster** [comment]
It looks like the problem is that the same instance of CommandLineApplication is being reused. Try changing your code to create a new instance of CommandLineApplication for each evaluation of the main loop. CommandLineApplication isn't currently designed to handle multiple calls of `.Execute()`.

By the way, this looks the same to me as https://github.com/natemcmaster/CommandLineUtils/issues/152. In that issue, we talked about adding support for REPL behavior, but no one came forward to help me implement it.

**Comment by shockliang** [comment]
I got it! I will making new instance for each evaluation.
Or making  an API to clear command state?

And I hope the REPL functionality will be built-in in the CommandLineUtils in the future. 👍 

Thank you for help Nate. 😄
