### ISSUE TITLE
Support forward slash on options

### ISSUE THREAD

**Issue by BrianCatlin** [natemcmaster/CommandLineUtils#263]
Please support forward slash ("/") to be more compatible with Windows applications, e.g. program.exe /a /b /c:stuff

**Comment by natemcmaster** [comment]
Looks like a duplicate of https://github.com/natemcmaster/CommandLineUtils/issues/3. There has been little interested in this over the last few years. I'm not really planning on doing this, but I'll leave it open for comment to see if there are others who would use this.

**Comment by kyle-rader** [comment]
I'm explicitly glad that windows centric concepts are not supported. It
helps the experience of tools we write be standard access platforms.

**Comment by BrianCatlin** [comment]
It's about offering choices. Why do you object to someone making choices that are different from your own? That's like saying that since you're on a diet, I cannot have chocolate cake

**Comment by natemcmaster** [comment]
Just to be clear...I'm not opposed to making it possible to parse Windows-style arguments, but I'd like to see if there is sufficient interest in this feature first

**Comment by kyle-rader** [comment]
I've actually changed my mind on this specifically for the help option. For my uses I have a large number of old style windows devs that are used to passing /? to get help and that not being valid is an accessibility issue. Once the help is printed it becomes obvious that `-` and `--` are the patterns to use and can this can help drive standardization. I will look at adding this.

**Comment by farangkao** [comment]
Also consider anyone who has to replace or support legacy software ,that have forward-slash style command Line parameters.

A simple solution would be to just replace all "/" with "--" before parsing it the normal way, 
that's of course not the most proper way, and would make usage of "/" in other places not be supported (but i think for most cases this would work)

**Comment by natemcmaster** [comment]
> For my uses I have a large number of old style windows devs that are used to passing /? to get help

It's been a while since I used Windows as a dev, but I remember that being a real pain. There are a mix of Windows-style, Unix, and PowerShell flavors and you have to mentally remember which is supported. In my own tools, I would probably not support anything other than `/?` which would only print usage, but I can understand why some may want to preserve compatibility with existing usage.

As I think I've said before, I'm open to this feature but lack motivation to build it myself. Comment on this thread if you want to contribute a pull-request and I can assign this issue to you :)
