### ISSUE TITLE
Running under Bash

### ISSUE THREAD

**Issue by paul-gauci** [natemcmaster/CommandLineUtils#273]
**Describe the bug**
Everytime the help is being displayed, a couple of empty lines are being displayed and asks me to press `q` to exit

**To Reproduce**
1. Ubuntu 19.04
2. DotNet Core 2.2
3. McMaster.Extensions.CommandLineUtils 2.3.4
4. Display `Help`

**Expected behavior**
Exits the command without pressing `q` and extra lines

**Screenshots**
![Screenshot_2019-09-08_20-27-37](https://user-images.githubusercontent.com/52675520/64492708-36922780-d277-11e9-819a-41bad4f4173c.png)

**Comment by natemcmaster** [comment]
This behavior is intentional. If you want to opt-out of using the help pager, set [`CommandLineApplication.UsePagerForHelpText`](https://natemcmaster.github.io/CommandLineUtils/v2.3/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication.html?#McMaster_Extensions_CommandLineUtils_CommandLineApplication_UsePagerForHelpText) to false.

Let me know if that doesn't work for you.
