### ISSUE TITLE
Implement interfaces to allow mocking for unit testing

### ISSUE THREAD

**Issue by matthewjones555** [natemcmaster/CommandLineUtils#304]
It would be useful if CommandLineApplication implemented an ICommandLineApplication interface, so it could be easily mocked, to facilitate unit testing applications that consume this API.

At the moment, you cannot mock CommandLineApplication, and it makes code that consumes it untestable.

Implementing an interface that covers the entire CommandLineApplication class is quite straightforward, and wouldn't cause any breaking changes as far as I know.

I'd be happy to submit a change in a pull request if this sounds reasonable to you.

Please let me know your thoughts on this.  I'm aware that you're considering refactoring the API in the future, but it would be helpful to have this new functionality before then.

**Comment by natemcmaster** [comment]
I'm not sure about the solution you've proposed. The problem with interfaces is that once you've defined them, you can never change them without breaking thing. New API is continually added to CommandLineApplication. Making an interface for it would prevent us from doing that anymore.

That said, let's explore alternatives to the testability issue. Would you mind sharing a sample of the kind of test code you are trying to write? It seems to me like it shouldn't be difficult to use CommandLineApplication with test code...I've done it a lot... so maybe I can suggest a different approach.

**Comment by matthewjones555** [comment]
> New API is continually added to CommandLineApplication. Making an interface for it would prevent us from doing that anymore.

Unless I'm mistaken, Interfaces only prevent you from changing the signature of existing methods.  You're free to add new members to interfaces without breaking your clients.  This is no different from your current scenario.  If you were to change an existing method on your concrete class, you'd introduce breaking changes for your clients, unless you add an overload (i.e. it would be a new method), or in some cases, if you use optional parameters.  Both of these approaches would also work even if you exposed an interface.

As requested, here are some examples, that make use of [Moq](https://github.com/Moq/moq4/wiki/Quickstart).

Here's an example where we check that the consuming class adds the correct command line options.

    var commandLineApplication = new Mock<ICommandLineApplication>();
    var myApplication = new MyApplication(commandLineApplication);
    // ensure that a command option is added, with a name of -OutputDirectory
    commandLineApplication.Verify(c => c.Option("-OutputDirectory", It.IsAny<string>(), CommandOptionType.SingleValue);

Here's an example where we mock up a failure code from _commandLineApplication.Execute(), so we can test what the application does under various simulated conditions.

    var commandLineApplication = new Mock<ICommandLineApplication>();
    // mock up a failure return code
    commandLineApplication.Setup(c => c.Execute(It.IsAny<string>())).Returns(1);
    var myApplication = new MyApplication(commandLineApplication);
    
    var result = myApplication.Run();
    // ensure the result we get is a failure
    Assert.AreEqual(ApplicationCode.Failure, result);

We can also simulate exceptions in the same way

    // mock up an exception
    commandLineApplication.Setup(c => c.Execute(It.IsAny<string>())).Throws<NullReferenceException>();

When writing unit tests, it's important to be able to mock classes up, so our tests do not end up running real code.  If we were to run real code, then we cannot easily determine if a failure in our test was due to a bug in our code, or a bug in the API that our code consumes.  It's important to not actually run the CommandLine library in my consumer unit tests, it is important to check instead what my consuming code will do under various simulated conditions.

**Comment by mzorec** [comment]
Completly agree with @matthewjones555 Would be really nice to have interfaces.

**Comment by natemcmaster** [comment]
Adding new members to an interface is a breaking change. This is a common misunderstanding about interfaces in .NET, and it creates problems. Read https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/breaking-changes#binary-breaking-change if you don't believe me, or read this thread https://github.com/natemcmaster/CommandLineUtils/issues/294#issuecomment-547741930 as a real-life example of this problem. (As a side note, this problem is actually the primary motivation for this feature in C# 8 --https://devblogs.microsoft.com/dotnet/default-implementations-in-interfaces/ -- but this only helps if you are exclusively on .NET Core 3 and newer. This feature isn't supported on all .NET Standard platforms, so I can't use unless I decide to drop support for older platforms from this library.)

I understand the need for mocks, but Moq isn't the only way to do that. I wrote a small test project to demonstrate how you could mock CommandLineApplication right now: https://gist.github.com/natemcmaster/28442cdc9390b2e630da6984022fbd6f. Is this approach sufficient for your needs?

**Comment by matthewjones555** [comment]
> Adding new members to an interface is a breaking change

This is only true if the consumer is **implementing** your interface.  It doesn't break for people that are just consuming the API.  I think re-implementing the API is a different use case altogether.

I understand your position, even if it's makes things a bit less convenient.

Personally, if I was implementing an interface from a library that has seen rapid changes and growth, I would expect to have to implement new members as the interface grows and evolves, but I make a point of not implementing interfaces that I do not have in depth knowledge of.

Your example of using inheritance to mock is an approach that I've used before, and had success with, I will have to try to remember limitations I've run into before, other than it being impossible with sealed classes.

Thank you for your time, and for your response.

**Comment by Tyrrrz** [comment]
I personally think providing library interfaces for the consumers to mock them is a design anti-pattern. Generalizing further, I'd say mock-based testing in general is an anti-pattern, but even then, you would want to mock your own service layer, not 3rd party dependencies. I would want to see an example of a test that attempts to mock `ICommandLineApplication` and actually does something useful.

Just my 5 cents.

**Comment by JakeSays** [comment]
I disagree with adding interfaces. Doing so actually makes the mocking process more complicated. The command line can easily be mocked by passing a customized command line to 'app.Execute()' during test setup.

**Comment by matthewjones555** [comment]
How does adding interfaces make mocking more complicated?  It makes it into a [1 line job](https://github.com/Moq/moq4/wiki/Quickstart).

```lang=csharp
var mock = new Mock<IFoo>();
```

That is the opposite of complicated.

**Comment by JakeSays** [comment]
@matthewjones555 in this situation it is more complicated than just passing a string of formatted arguments. It certainly isn't worth providing interfaces for that purpose. As others have mentioned it is not the purview of a library to provide mocking capabilities.

**Comment by matthewjones555** [comment]
> @matthewjones555 in this situation it is more complicated than just passing a string of formatted arguments

In unit testing, we ideally only want to test the code that we're testing.  Tests usually only check that they are consuming APIs of dependencies correctly.  Ideally tests should not execute any "real code", i.e. there should be no real web requests made, no real database requests, no real threads created, and in this case, no real command line parsing.

This allows us to be certain that the code we're testing is only the layer that we're interested in.  When we get a test failure, we want to be sure that it indicates a problem with said layer, and not a problem with any code that we're calling.  A failure in a dependency should not trigger false positives in the layer being tested.

The assumption is that any code that our layer calls is already tested, i.e. our tests obey the single responsibility principle, to test only the layer we're interested in.

> it is not the purview of a library to provide mocking capabilities.

I agree, but it is a nice courtesy of them to do so, as it encourages good practice, and also ensures that your own code is testable.

**Comment by Tyrrrz** [comment]
Reading the comments in this thread really makes me want to write a blog post titled "Stop writing unit tests" that emphasizes what's wrong with it and what are the better alternatives. You should only rely on mocking if you have literally no other way to test your code. If the library/framework/whatever offers you a way test your software with all of its dependencies in a fast and deterministic fashion, you should always use that instead. Ideally the tests shouldn't "only test the code they're testing" (what else are they going to test anyway?) but rather reflect the behavior of the user as close as possible to verify and ensure that there are no discrepancies in relation to the software specification (written, assumed, or otherwise) which would be perceived by the user as bugs.

**Comment by matthewjones555** [comment]
> but rather reflect the behavior of the user as close as possible

That style of testing is valid, but is certainly not a replacement for unit testing.

> You should only rely on mocking if you have literally no other way to test your code

There are many ways to test code, and multiple approaches should be used to complement each other to ensure that the quality of your product.  Unit testing isn't a silver bullet, it has a very specific job, and is often misunderstood.

I fail to understand the overt hostility in this thread.  I have _politely_ asked the library author if he could expose some interfaces for me, and he _politely_ declined as is his prerogative.

You don't want to write unit tests?  Good for you.  I **_do_** want to write unit tests, and I want to be able to easily mock my dependencies without implementing a concrete class each time.

**Comment by Tyrrrz** [comment]
To be fair, I wasn't (trying to be) hostile to anyone in this thread, but it's very easy to get that impression from an argument, especially one being held online. My opinion here is that a lot of people attribute too much value to unit tests because of the "clean code" software design cargo cult. If you genuinely have a scenario where you literally can't write a functional test that provides a good level of confidence while being deterministic and maintainable, I would be really curious to know what it is you're testing and how, because I have almost never experienced that, especially with a CLI framework.

**Comment by matthewjones555** [comment]
> If you genuinely have a scenario where you literally can't write a functional test that provides a good level of confidence while being deterministic and maintainable

I don't have such a scenario, but functional tests fulfil a different requirement to unit testing, they're different tools for different purposes.  They're best used to complement each other, not supplant each other.

If you've not got the time or budget to develop unit tests, or you just don't like them, then that's fair enough, they're absolutely not a requirement, but we _do_ use them in my team, and we find them valuable, and that's also fair enough.

**Comment by JakeSays** [comment]
@matthewjones555 I am definitely not suggesting that unit tests aren't necessary, or that mocking is a bad/unnecessary practice. I just believe that in this scenario mocking an interface is not the most efficient method.

Unit tests are most often considered second class citizens because few people enjoy writing and maintaining them, so I try to keep things as simple as possible. This is especially true when it comes to introducing junior/new developers to a code base.

But as you stated you asked and the author declined, and I agree that this isn't the place for a philosophical discussion on the merits of unit testing methodologies. My apologies for taking the discussion in that direction.

**Comment by natemcmaster** [comment]
I'm going to close this as I don't plan to add an interface for `CommandLineApplication` for reasons suggested above in https://github.com/natemcmaster/CommandLineUtils/issues/304#issuecomment-551029189. I believe it is possible to make tests work with this library without adding interfaces. Try structuring your code to encapsulate CommandLineUtils parsing in a way that isolates it from the functionality of your code that you want to test. I've found the adapter pattern and proxy patterns useful for this kind of testing. I'm happy to provide more code snippets if you're not sure how to apply these patterns.

That said, if you come across other code which is impossible to encapsulate in a test (like any usages of global, static singletons), please let me know.

**Comment by ppadial** [comment]
I'm late to the party, but i have done a wrapper to make my CliApps testable:
https://github.com/ppadial/dotnet/tree/master/src/dotnet.cli

and a sample:

https://github.com/ppadial/netcore3-cli-sample
