### ISSUE TITLE
An open call for contributors

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/CommandLineUtils#312]
I am interested in having more contributors help me work on this project. There is room for improvement on this library, and I'm not planning to do it myself anytime soon. I don't have much time to work on open source anymore. I recently became a new father and also a new job which requires 2 hours of commuting. As you can imagine, I don't have much free time. If you are interested in helping, please let me know.

Cheers,
Nate

**Comment by natemcmaster** [comment]
Update:

To make it easier to jump in, I am going to try and be more transparent about how this project works...including making pull requests for all of my own work and using issues to layout my plans. See #314 for an update to the contributing guide. See #315 for details on plans for the next release.

**Comment by jzabroski** [comment]
You're the best @natemcmaster !  You'll find formalizing things will actually help you tap into higher level brain skills.  At least, that's why I formalize things.

**Comment by jzabroski** [comment]
In terms of contributing, I'll be honest, I'm a fan of JT Arquino's Command Line Utils . https://github.com/dotnet/command-line-api

It would be helpful to know how you see things fitting together.  As an ex-Softie, you know better than me on what will survive.

**Comment by natemcmaster** [comment]
Thanks @jzabroski ! 

I can understand hesitance to jump into a project when a better-funded alternative is out there. I was one of the early contributors at the inception for https://github.com/dotnet/command-line-api. I considered using it under the hood in this library https://github.com/natemcmaster/CommandLineUtils/issues/201, but decided against it as the library continues to remain in an alpha, unsupported state. I can only speculate on what will become of that project, but my guess is it will remain experimental for another year, if not more.  It’s been undergoing development for almost 2 years with no clear release schedule or roadmap. See https://github.com/dotnet/command-line-api/issues/700. I like some of the things the library does but it’s not something I would use myself today.

In terms of what I’m hoping for from contributors, I currently trying to feel out if there are features people really want to see added here. There are a few dozen issues open, but so far no one has volunteered to do the work. I’m open to contributions, and want people to know that.

**Comment by vpkopylov** [comment]
@natemcmaster Thank you for this library! I've used it in one of my projects and find it very useful. I've been following the repo for a few months and I can say that you are a great maintainer! It's sad that you've decided to stop working on the project, Hope you'll find at least a little time for it in the future. 
Although I've fixed a few minor bugs, I don't have in-depth knowledge of the internals of the library.  I'm pretty busy myself, but I'll take a look at the open issues to find where I can help.

**Comment by natemcmaster** [comment]
I'm going to keep paying attention to incoming issues and pull requests. I appreciate your contributions in the past, @vpkopylov ! Your willingness to fix issues is exactly the kind of help I'm hoping to get from the other users of this library.

**Comment by jzabroski** [comment]
@natemcmaster I'm not a big fan of any command line library, so far - but I am a fan of you and your work and appreciate your commitment to "get it right".  If you're open to brainstorming an idealized Command Line API, I am very interested in writing an API that is maintainable, powerful, and fun to use.  Jon's System.CommandLine project is certainly an inspiration, but I had similar ideas before his project took off.

1. Using the Microsoft Prose SDK to memoize suggestions.
2. Command Line APIs should be able to export their help as json objects, similar to how `docker inspect` works.
3. You can then write a bash/PowerShell alias for your command in one line of code, where it adds to your profile an alias with auto-complete based on your exported json object.
4. When the json alias layer fails, it could fall back to Prose SDK for suggestions on what you meant to type - or just use Levenshtein distance to find the right command, etc.
5. For Windows, turn on security auditing flags in the Windows Event Log that enable tracing all command line calls, and feed that into the Prose SDK.

In terms of general feedback, I don't like SubCommands, because they're not really composable.  As an analogy, the .NET Task API doesn't have SubTasks.

In terms of general expressiveness, I like FluentCommandLineParser (FCLP) nuget package.  It is very nice to write.

**Comment by natemcmaster** [comment]
@jzabroski - I'm interested in your suggestions above and would be happy discuss more. Suggestion 2 is the only one I had considered before (#4) but didn't implement due to lack of apparent interest. The others are new ideas that deserve a separate thread.

Re: "getting it right". I'm not sure there is a "right" when it comes to command line parsers. I've seen a dozen versions of command line libraries over the years, including multiple editions of System.CommandLine by the .NET Team at Microsoft. All of these libraries have good and bad, and I suspect future libraries will be the same. At the moment, I'm not looking to build yet-another command line parser.

That said, I am committed to incremental improvements to this library, and open to suggestions on how to do that. This library has flaws - some of my own doing and others I inherited. (In case you didn't know, this code is a fork of a fork. The earliest version of this code on GitHub is about 6 years old - https://github.com/aspnet/dnx/commit/51550e8567b9b94d2dddfdd87830fe2d6138cc12 - the code has moved through multiple namespaces, repos, and NuGet packages over the years. I'm the current custodian because no one at Microsoft was willing to support it.) I'm planning to continue maintenance of this project, and helping guide new contributors on building new features, but I don't plan on writing any new features myself in the near future.

**Comment by natemcmaster** [comment]
Thanks for your replies so far! I've written up my thoughts about where this project goes from here in https://github.com/natemcmaster/CommandLineUtils/issues/327

Closing this as I think I got my point across - this project is open-source and open for contributions. If you'd like to help out, checkout these issues: https://github.com/natemcmaster/CommandLineUtils/labels/help%20wanted
