### ISSUE TITLE
[Question] Defining Options in Base Class and using them in derived class

### ISSUE THREAD

**Issue by alexhughes05** [natemcmaster/CommandLineUtils#520]
In my application I have a base class that defines several different options which represents commands I want to use in several different derived classes. However, when I insert the command-line arguments and run my application, these options are null. Their values never get set. This is interesting because options I define in the derived class work fine, their values are propagated as intended. It's only when I try to use an option from a base class in a derived class that I have issues. Is this something that is supposed to happen?

**Comment by StelioKontosXBL** [comment]
It sounds like you are describing the functionality shown in the [Subcommands using inheritance sample](https://github.com/natemcmaster/CommandLineUtils/blob/main/docs/samples/subcommands/inheritance/Program.cs). Have you cross referenced your implementation with that of the sample?

If you're still having issues, provide a condensed example of your implementation along with the arguments and output that exhibit the described unexpected behavior. Without context, it's hard to say, but it sounds like you're dealing with a nuance between **shared functionality** (eg using derivation to provide a commonly used option such as `--verbosity` to multiple otherwise-unrelated commands) and **shared state** (accessing the value assigned to a parent command's option from inside a subcommand, such as in the sample below).

https://github.com/natemcmaster/CommandLineUtils/blob/main/docs/samples/subcommands/inheritance/Program.cs#L71-L85
