### ISSUE TITLE
Parsing should not use current culture by default

### ISSUE THREAD

**Issue by rubenprins** [natemcmaster/CommandLineUtils#60]
Currently, value parsers use the current culture for parsing (that is: no culture is specified). This means that on systems not running on an en-US locale, problems will occur because scripts & response files are non-portable (my 1.234 is your 1,234 and vice versa, and the same with dates).

If all parsing code were to use the Invariant culture by default, these problems would disappear.

**Comment by atruskie** [comment]
Hi @rubenprins. 

So I'm running on an en-AU locale and for us, the Invariant culture is not a solution either (particularly because its standard format for dates is MM/dd/yyyy!). I'd also suggest that the Invariant culture is not suitable for interfaces (including command line interfaces) as it was explicitly designed to cater for "formatting and parsing operations that **persist** formatted data, " (emphasis mine).

Your use case is valid and has merit but I have a different one (not suggesting mine is more important just that we have different requirements). In my case, while 95%+ of the invocations of my CLI are done by a script (which would benefit from a fixed culture), my "scripts" represent only one "user" of the 200+ worldwide human users that experiment with my CLI. In those cases, flexibility in interacting with humans in their current culture is desired.

But I hope this discussion is moot. With the changes in #59, you can replace all the inbuilt value parsers with ones that use exact parsing semantics. While that might seem to be a bit of a task, you only need to replace two of the inbuilt ones (`double` and `float`) for your use case.

**Comment by rubenprins** [comment]
While I agree that the choice of date format for the Invariant culture is unfortunate (the Invariant culture *is* the en-US culture, for all intents and purposes, in "good" IT tradition), it does allow passing of ISO yyyy-mm-dd dates, IIRC. As do most other cultures.

Also, note that I said *by default*. There is no way of changing this implicit default, apart from, like you suggest, replacing all affected parsers (float, double, decimal, DateTime).

And as a European, I have faced too many cases where defaults such as these break tooling, as programmers developing only under en-* locale have no idea their program is broken for those running under a locale that uses mirrored number separators (like Dutch, French and German). And you *can't* change the default locale for just the next program invocation from inside a script to fix this.

So it's not so much that I want this for the tools *I* develop, but for tools others develop and I want to use.

Now, if there was an ISO culture built into the framework, rather than this weird Invariant culture, and we took that the default, I don't think we would be having this argument...

**Comment by natemcmaster** [comment]
What if we added the ability to specify a culture info to be used by the parsers? I think current culture is the best default, but realize this is not ideal for everyone. Seems like something you should be able to override.

**Comment by atruskie** [comment]
That seems reasonable to me. I've got some more time to contribute if you like - I'm keen to wrap up these tweaks before I move from my hacky custom build back to the main build.

Is this as simple as adding `ParsingCulture` property to `ValueParserProvider` and an extra `CultureInfo culture` argument to `IValueParser.Parse`?

**Comment by atruskie** [comment]
Since we seem to be chasing each other's time zones, I had a go at what I thought was best in #63. Happy to change anything you want to be changed.
