### ISSUE TITLE
app.ShowVersion does not produce output

### ISSUE THREAD

**Issue by tooh** [natemcmaster/CommandLineUtils#64]
app.ShowVersion();

**Comment by natemcmaster** [comment]
Did you set FullName or LongVersionGetter?

https://github.com/natemcmaster/CommandLineUtils/blob/54a7f5870888a787892242755d78390353983a96/src/CommandLineUtils/CommandLineApplication.cs#L693-L696

**Comment by tooh** [comment]
Thx for reply.
Sorry I'm a bit of a newbie in c#. Started using it on MacOs recently.  So can you give some more guidance please ?
I have set a version number in de project properties. I don't know what you mean with 

> Did you set FullName or LongVersionGetter?
I try to achieve the following:

`Usage: ClienteleCLI [options]
**Version : 1.0.0**
Options:
  -?|-h|--help            Show help information
  -s|--summary <SUMMARY>  The summary
  -n|--notes <NOTES>      Notes
  -t|--type <TYPE>        Support call type
`

**Comment by natemcmaster** [comment]
@tooh happy to help. Here is a minimal program that would produce help output similar to what you said you want to achieve.
```c#
using McMaster.Extensions.CommandLineUtils;

public class Program
{
    public static int Main(string[] args)
    {
        var app = new CommandLineApplication
        {
            FullName = "ClienteleCLI",
            Name = "ClienteleCLI",
        };

        app.HelpOption();
        app.VersionOption("--version", "1.0.0");
        app.Option("-s|--summary <SUMMARY>", "The summary", CommandOptionType.SingleValue);
        app.Option("-n|--notes <NOTES>", "Notes", CommandOptionType.SingleValue);
        app.Option("-t|--type <TYPE>", "Support call type", CommandOptionType.SingleValue);

        return app.Execute(args);
    }
}
```
The help output for `dotnet ClienteleCLI.dll --help`
```
ClienteleCLI 1.0.0

Usage: ClienteleCLI [options]

Options:
  -?|-h|--help            Show help information
  --version               Show version information
  -s|--summary <SUMMARY>  The summary
  -n|--notes <NOTES>      Notes
  -t|--type <TYPE>        Support call type
```

It's not exactly what you said you would like, but it's pretty close. Let me know if you have more questions.

**Comment by tooh** [comment]
OK, thx, that makes it clear. Works for me for now.

On the wishlist to get the version number from the project properties instead of the hardcoded string.

Issue  can be closed.

**Comment by natemcmaster** [comment]
>  project properties 

That's supported too :) See [docs here](https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.html?q=Version#McMaster_Extensions_CommandLineUtils_CommandLineApplicationExtensions_VersionOptionFromAssemblyAttributes_McMaster_Extensions_CommandLineUtils_CommandLineApplication_System_Reflection_Assembly_) and [implementation here](https://github.com/natemcmaster/CommandLineUtils/blob/40b5a3677db125f114daa7da3279c5f2e67ad0fe/src/CommandLineUtils/CommandLineApplicationExtensions.cs#L143-L180). It should be pretty easy to use assembly attributes instead of a hard-coded string. These assembly attributes are typically automatically generated when you use .NET Core, but can also be set using AssemblyInfo.cs
```
app.VersionOptionFromAssemblyAttributes(typeof(Program).Assembly)
```

Closing, but let me know if you have more questions
