### ISSUE TITLE
How to get the value of the selected option ? 

### ISSUE THREAD

**Issue by tooh** [natemcmaster/CommandLineUtils#71]
I started using .Accepts()  and created this option

```
var optionCallType = app.Option("-t|--type <TYPE>", "Support call type I , R, S or P", CommandOptionType
                                    .SingleValue)
                                    .Accepts().Values("I", "R", "S","P");
```
Before refining the code with Accepts() to limit the input I could get the value of the option with:

```
calltype = optionCallType.Value();
```
This does not work any more. (I use the latest RC). 

Please assist.

**Comment by natemcmaster** [comment]
You are probably getting a compiler error, right? This is because the [return type of `.Values(param strings[]`](https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.ValidationExtensions.html?q=ValidationExtensions#McMaster_Extensions_CommandLineUtils_ValidationExtensions_Values_McMaster_Extensions_CommandLineUtils_Validation_IValidationBuilder_System_String___)  and [`.Accepts()`](https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.ValidationExtensions.html?q=ValidationExtensions#McMaster_Extensions_CommandLineUtils_ValidationExtensions_Accepts_McMaster_Extensions_CommandLineUtils_CommandOption_) is an `IValidationBuilder`, not a `CommandOption`. To fix this, you can use a [different overload of `.Accepts`](https://natemcmaster.github.io/CommandLineUtils/api/McMaster.Extensions.CommandLineUtils.ValidationExtensions.html?q=ValidationExtensions#McMaster_Extensions_CommandLineUtils_ValidationExtensions_Accepts_McMaster_Extensions_CommandLineUtils_CommandOption_System_Action_McMaster_Extensions_CommandLineUtils_Validation_IOptionValidationBuilder__) which takes a lambda to configure the validation and still returns `CommandOption`.
```c#
.Accepts(v => v.Values("I", "R", "S","P"));
```

**Comment by tooh** [comment]
Again thx for the reply. I am not sure if I completely understand this concept, but made it working by applying your suggestion.

Can be closed.
