### ISSUE TITLE
VersionOption doesn't ever use the short getter

### ISSUE THREAD

**Issue by atifaziz** [natemcmaster/CommandLineUtils#94]
## Steps to Reproduce

1. Clone this repo (at commit 92481fac0cf8ccc8345af7f785a4a50d29675534 at time of reporting)
2. Build the solution using `build.cmd`
3. Run C# Interactive (`csi.exe`)
4. Add reference to `McMaster.Extensions.CommandLineUtils.dll` via `#r`
5. Execute the following:
    ```c#
    using McMaster.Extensions.CommandLineUtils;
    var app = new CommandLineApplication(throwOnUnexpectedArg: false);
    app.VersionOption("-v|--version", () => "version (short)", () => "version (long)");
    app.Execute(new[] { "-v" });
    app.Execute(new[] { "--version" });
    ```

## Expected Output

Expected the line `app.Execute(new[] { "-v" });` to print `version (short)` and the line `app.Execute(new[] { "--version" });` to print `version (long)`.

## Actual Output

```
Microsoft (R) Visual C# Interactive Compiler version 2.7.0.62715
Copyright (C) Microsoft Corporation. All rights reserved.

Type "#help" for more information.
> #r "A:\CommandLineUtils\.build\bin\McMaster.Extensions.CommandLineUtils\Debug\net45\McMaster.Extensions.CommandLineUtils.dll"
> using McMaster.Extensions.CommandLineUtils;
> var app = new CommandLineApplication(throwOnUnexpectedArg: false);
> app.VersionOption("-v|--version", () => "version (short)", () => "version (long)");
> app.Execute(new[] { "-v" });
version (long)
> app.Execute(new[] { "--version" });
version (long)
```

Both of the following lines:

```c#
app.Execute(new[] { "-v" });
app.Execute(new[] { "--version" });
```

print `version (long)`, which is incorrect. There seems to be no way to distinguish between the two when `VersionOption` specifically allows one to have a short and a long getter.

**Comment by atruskie** [comment]
Hey @atifaziz, I'm not too sure of how it should work myself, but it seems strange that any short/long form for the same option should have different behaviour.

From the code, it seems the intention was rather that `LongVersionGetter` is used when outputting the version only, and `ShortVersionGetter` is used as part of the name output by `GetFullNameAndVersion`:

https://github.com/natemcmaster/CommandLineUtils/blob/92481fac0cf8ccc8345af7f785a4a50d29675534/src/CommandLineUtils/CommandLineApplication.cs#L782-L813

I suspect this is not a bug but rather some ambiguous naming.

**Comment by atifaziz** [comment]
> I suspect this is not a bug but rather some ambiguous naming.

That could be but it feels like a bug when `VersionOption` allows for both.

> seems strange that any short/long form for the same option should have different behaviour.

Not a different behaviour but different output. For example, the long form could produce a more verbose output:

    $ app --version
    App 1.0.0 (2afb383)

whereas the short form would be used to print _just_ the version number in a machine-parsable manner:

    $ app -v
    1.0.0

The fix would be very straightforward. Have a `ShowVersion` overload that specifies whether the long or short format should be displayed:

```c#
/// <summary>
/// Displays version information that includes <see cref="FullName"/> and <see cref="LongVersionGetter"/>.
/// </summary>
public void ShowVersion()
{
    ShowVersion(false);
}

/// <summary>
/// Displays version information that includes <see cref="FullName"/> and <see cref="LongVersionGetter"/>.
/// If <paramref name="inShortFormat"/> is <c>true</c> then only the return value of
/// <see cref="ShortVersionGetter"/> is displayed instead.
/// </summary>
public void ShowVersion(bool inShortFormat)
{
    for (var cmd = this; cmd != null; cmd = cmd.Parent)
    {
        cmd.IsShowingInformation = true;
    }

    if (!inShortFormat)
    {
        Out.WriteLine(ShortVersionGetter());
    }
    else
    {
        if (!string.IsNullOrEmpty(FullName))
        {
            Out.WriteLine(FullName);
        }

        Out.WriteLine(LongVersionGetter());
    }
}
```

Then the following line in `CommandLineProcessor` would have to be changed from:

https://github.com/natemcmaster/CommandLineUtils/blob/92481fac0cf8ccc8345af7f785a4a50d29675534/src/CommandLineUtils/Internal/CommandLineProcessor.cs#L174

to:

```c#
_currentCommand.ShowVersion(arg.Type == ParameterType.LongOption);
```

If that makes sense then I'm happy to submit a PR.

**Comment by atruskie** [comment]
So @natemcmaster is the maintainer and it is their call. (I just thought I could offer some helpful advice 😃 )

However, a different output (which is a different behaviour) for the same option still seems incorrect. Here's a small app the does what you want in a more conventional approach:

```
        var app = new CommandLineApplication(throwOnUnexpectedArg: false);
        app.FullName = "My CLI app";
        app.VersionOption("--version", () => "version (short)", () => "version (long)");
        var shortVersion = app.Option("-v", "Print the short version and quits", CommandOptionType.NoValue);

        app.OnExecute(
            () =>
            {
                if (shortVersion.HasValue())
                {
                    Console.WriteLine("v1.2.3.4");
                    return 0;
                }

                Console.WriteLine(app.GetFullNameAndVersion());
                return 0;
            });

        return app.Execute(args);
```

And the output:
```
>dotnet .\HelloWorld.dll
My CLI app version (short)
>dotnet .\HelloWorld.dll --version
My CLI app
version (long)
>dotnet .\HelloWorld.dll -v
v1.2.3.4
```

**Comment by atifaziz** [comment]
> However, a different output (which is a different behaviour) for the same option still seems incorrect.

`git log -h` vs. `git log --help`. 🤔 

> Here's a small app the does what you want in a more conventional approach

Thanks, just would like to avoid all that boilerplate in every app.

> @natemcmaster is the maintainer and it is their call.

Perhaps let's wait for him to chime in.

**Comment by natemcmaster** [comment]
The existence of a long and short version is something that came along when forking this project. Personally, I've never found a good use case for having two separate version strings. I was considering dropping it altogether in the next major version 3.0 because I think having two version strings is confusing. If someone can make a compelling argument for keeping it, I'd love to hear it.

@atifaziz what kind of behavior are you trying to achieve? Is this issue preventing you from getting the output you want? Or is it just something you've noticed while playing with the library?

**Comment by atifaziz** [comment]
> what kind of behavior are you trying to achieve?

[I gave an example earlier](https://github.com/natemcmaster/CommandLineUtils/issues/94#issuecomment-385661237). The idea is to emit a longer, human-readable version versus something brief that is machine-readable for shell scripts.

> Is this issue preventing you from getting the output you want?

Yes, otherwise I wouldn't have reported it. :wink: I just thought it was supported given the signature of the `VersionOption` method so felt like a bug when the behaviour turned out to be different at runtime.

> I think having two version strings is confusing.

Not sure how that is. You should get the same version number either way so it won't confuse the user. The only difference is that the short version would output _just_ the version number. The long format could add the program name, some repo hash or date of the build, dependency versions of statically linked components, etc. Here's an example of a long format:

```
GNU hello 2.3.0
Copyright (C) 2007 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

However, the short format would be just:

```
2.3.0
```

This could be used by a script without any grep-ing to check if the right version of a program is installed.

**Comment by atruskie** [comment]
Just a prelude to this post: it's long because I'm trying to help - I have a habit of sounding cold in text so I hope I don't come off that way 😄 

I'm strongly opposed to the idea that the same option should have different behaviours based on whether the short or long version is used. The essential notion of short forms is that they are synonyms of the long forms; i.e. in the following case:

```
-v|--version                   Show version information
```

should always do the same thing, no matter how it is invoked (`-v` or `--version`). 

However:

```
-v                             Show short version information
--version                      Show long version information
```

is a perfectly acceptable choice because they are different options (and are no longer synonyms of each other). Earlier the example of `git log -h` vs `git log --help` was cited as a seemingly incongruent example; they, in fact, aren't and follow the behaviour of my second example. Internally git rewrites the `--help` flag to invoke `git help` (see [git help docs](https://git-scm.com/docs/git-help)). The [`--help`](https://github.com/git/git/blob/1f1cddd558b54bb0ce19c8ace353fd07b758510d/git.c#L543) option is a separate option from the [`-h`](https://github.com/git/git/blob/1f1cddd558b54bb0ce19c8ace353fd07b758510d/git.c#L319) option.

To further use git as an analogy, git only has a `--version` option, which prints the name and version:
```
> git --version
git version 2.16.2.windows.1
> git -v
Unknown option: -v
```

# Current state

Currently only one single `Option` is defined for the version information, hence why differing output based on the long or short form would be inadvisable.

As far as I can tell, the only reason there is `ShortVersion` and `LongVersion` strings is so that the long version can be used in the `--version` output and the short version can be used as part of `GetFullNameAndVersion` which is intended to be used in a program header. They aren't related to the short and long form option flags at all.

The current behaviour is not a bug. In fact the defaults in this library are great and match other tools (like git).

# Compromises

## 1. No changes
As in my [previous comment](https://github.com/natemcmaster/CommandLineUtils/issues/94#issuecomment-385665685) it is easy to get the behaviour you want by adding the extra option yourself. 

## 2. More flexibility in `ShowVersion()`
My suggestion here is that the `ShowVersion()` method should execute a callback so the user can customize the output however they like. The default call back should match today's behaviour:

```
(app) => return app.FullName + "\n" + app.LongVersionGetter();
```

And someone could customize it:
```
(app) => app.LongVersionGetter();
```

Or if you really want to:
```
(app) => someLogicToDetermineIfShortOption ?  app.LongVersionGetter() : app.FullName + app.LongVersionGetter();
```

Note: I used `someLogicToDetermineIfShortOption` because the parser does not even retain the information needed to determine if the _same option_ was invoked from the short or long form.

## 3. Multiple version options

We could allow for two version options to be registered, with different templates and different callbacks. I'm not really a fan of this idea though since you could just as easily do it with option No.1. It might reduce some boiler plate though 🤷‍♂️ 

```
app.AddVersionOption("-v", () => "1.2.3.4");
app.AddVersionOption("--version", () => "My long version 1.2.3.4+git-abcde12");
```
---

Lastly, I agree with @natemcmaster that the `shortFormVersion` and `longFormVersion` should be removed. 

Not to speak for anyone, but I like the general trend this library has of setting sensible defaults that can be changed. If you want different formatting for your version, don't use the default version option. Or, if my idea No.2 from above is implemented, customise the output.

I didn't even use version and fullname functionality from the library until recently because they didn't do what I wanted - instead I customized behaviour using the extensibility points that were already availabe and added my own output.

**Comment by natemcmaster** [comment]
Ok, how about this as a hotfix to unblock you @atifaziz? --> #96 

@atruskie you're comments connect well with some refactoring I've been considering. I don't like that `--version` and `--help` are special-cased in the parser. As we've discovered, it makes it hard to extend and customize their behavior, or to add your own version/help options. Users end up putting code at the top of the OnExecute block to check for "special" options. Maybe that's okay, but I was thinking of generalizing this behavior; I just haven't landed on an implementation I like yet.

**Comment by atifaziz** [comment]
@atruskie Thanks for the very detailed and awesome response.

> Earlier the example of `git log -h` vs `git log --help` was cited as a seemingly incongruent example; they, in fact, aren't and follow the behaviour of my second example. Internally git rewrites the `--help` flag to invoke `git help` (see [git help docs](https://git-scm.com/docs/git-help)). The `--help` option is a separate option from the -h option.

I'm well aware of this but you have to admit, irrespective of what it does under the hood (for the curious few who bother to read the help on help and pop and look under the hood) is irrelevant because the end effect is that to the uninformed user, `-h` appears like an alias for `--help`. Now we can argue whether that's intended or it's really two separation options (which I think what it is):

    -h        Show a summary of usage and common options
    --help    Show detailed help documentation


> I'm strongly opposed to the idea that the same option should have different behaviours based on whether the short or long version is used. The essential notion of short forms is that they are synonyms of the long forms

I'm not arguing for long and short forms should do different things. As far as version display goes, there are different ways to go about it like you suggested. I'd even say the following is confusing:

```
-v                             Show short version information
--version                      Show long version information
```

What I'd rather is see combining options. Suppose:

```
-v|verbose                     Show verbose output
--version                      Show version information
```

So if you use `--version`, you get the short version display. If you specify `--version` with `-v` or `--verbose` then you get a more detailed display. You can also go the other way if you have a `-q` or `--quiet` option, where `--version` will give you the longer display by default but combined with `-q` or `--quiet` will give the short machine-readable format. I can even imagine `--version --machine`.

Anyway, I think we've gone a bit off track here. The issue title reads, “VersionOption doesn't ever use the short getter” and that's all I meant to highlight as a bug. I didn't want to argue here the merits or perils of using the long and short form of an option to change the display of what is logically the same information. Even if I was to argue that, it would be confined to version and version display only. I would never say suggest that an application should use long and short forms as a general approach to switch between machine-readable and human-readable output. It's much better to have an explicit option to flag that and version display doesn't have to be an exception to that rule. I guess `VersionOption` mislead me there given its signature and I can admit that I was being mischievous 😇 and taking advantage of (what appeared to be) its support for long and short version display.

**Comment by atifaziz** [comment]
> Ok, how about this as a hotfix to unblock you @atifaziz? --> #96

#96 is fine on its own but it's unrelated to this. It's about an API that's confusing in its usage, intent and result.

**Comment by atifaziz** [comment]
Rude bots. 😄
